# Generated by Django 4.2.6 on 2024-01-04 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('level', models.IntegerField(default=0)),
                ('rank', models.CharField(max_length=15)),
                ('division', models.IntegerField(default=4)),
                ('champion', models.CharField(max_length=25)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('vision', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MainPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MatchupApp.player')),
                ('forward', models.IntegerField()),
            ],
            bases=('MatchupApp.player',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatchupApp.player')),
            ],
        ),
    ]
