# Generated by Django 5.0.1 on 2024-01-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_room_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_sumLevel',
            field=models.IntegerField(default=0),
        ),
    ]
