# Generated by Django 5.0.1 on 2024-01-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_match_user_sumlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_role',
            field=models.CharField(default=5, max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
