# Generated by Django 5.0.1 on 2024-01-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_match_user_role_alter_match_user_sumlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user_role',
            field=models.CharField(default=5, max_length=8),
        ),
    ]
