# Generated by Django 5.0.1 on 2024-01-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_match_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opp_role',
            field=models.CharField(default=5, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='opp_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
