# Generated by Django 5.0.1 on 2024-01-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_match_opp_role_match_opp_sumlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opp_tag',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='opp_username',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='match',
            name='tag',
            field=models.CharField(default='', max_length=5),
        ),
    ]
