# Generated by Django 5.0.1 on 2024-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_match_opp_tag_match_opp_username_alter_match_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ally1_role',
            field=models.CharField(default=5, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_tag',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_username',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_role',
            field=models.CharField(default=5, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_tag',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_username',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_role',
            field=models.CharField(default=5, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_tag',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_username',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_role',
            field=models.CharField(default=5, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_tag',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_username',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_role',
            field=models.CharField(default=5, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_tag',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_username',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_role',
            field=models.CharField(default=5, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_tag',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_username',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_role',
            field=models.CharField(default=5, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_tag',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_username',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_role',
            field=models.CharField(default=5, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_sumLevel',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_tag',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_username',
            field=models.CharField(default='', max_length=16),
        ),
    ]
