# Generated by Django 5.0.1 on 2024-02-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_match_ally1_assists_match_ally1_deaths_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='host_assists',
            new_name='user_assists',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='host_deaths',
            new_name='user_deaths',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='host_kills',
            new_name='user_kills',
        ),
    ]
