# Generated by Django 5.0.1 on 2024-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_host_assists_match_user_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_kda',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
