# Generated by Django 5.0.1 on 2024-02-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_match_user_kda'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ally1_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy1_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy2_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy3_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='enemy4_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='opp_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='opp_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='opp_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='opp_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='opp_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='opp_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='user_GPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='user_KP',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='user_KPM',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='user_VWBought',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='user_wardsKilled',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='user_wardsPlaced',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
