# Generated by Django 5.0.1 on 2024-02-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_match_ally1_gpm_match_ally1_kp_match_ally1_kpm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='ally1_KPM',
            new_name='ally1_DPM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='ally2_KPM',
            new_name='ally2_DPM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='ally3_KPM',
            new_name='ally3_DPM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='ally4_KPM',
            new_name='ally4_DPM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='enemy1_KPM',
            new_name='enemy1_DPM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='enemy2_KPM',
            new_name='enemy2_DPM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='enemy3_KPM',
            new_name='enemy3_DPM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='enemy4_KPM',
            new_name='enemy4_DPM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='opp_KPM',
            new_name='opp_DPM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='user_KPM',
            new_name='user_DPM',
        ),
    ]
