# Generated by Django 5.0.1 on 2024-02-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_ally1_kpm_match_ally1_dpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ally1_blurb1',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_blurb2',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_blurb3',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally1_blurb4',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_blurb1',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_blurb2',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_blurb3',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally2_blurb4',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_blurb1',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_blurb2',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_blurb3',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally3_blurb4',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_blurb1',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_blurb2',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_blurb3',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='ally4_blurb4',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='user_blurb1',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='user_blurb2',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='user_blurb3',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='match',
            name='user_blurb4',
            field=models.CharField(default='', max_length=85),
        ),
    ]
